version: '3.1'

services:
  django:
    build: backend/
    command: /start_dev.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    env_file:
      - '/backend/.env'
    image: postgres
    restart: always
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:9000"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django

volumes:
  postgres-data:
    driver: local
