version: '3.1'

services:
  django:
    build: backend/
    command: /start_dev.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    env_file:
      - '/backend/.env'
    image: postgres
    restart: always
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:9000"

  vue-dev:
    build: frontend/
    # working_dir: /app
    # command: [ "npm", "run", "serve" ]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
volumes:
  postgres-data:
    driver: local
