# Generated by Django 3.2.8 on 2021-11-29 09:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.URLField()),
                ('area', models.TextField()),
                ('address', models.TextField()),
                ('capital', models.TextField()),
                ('empNo', models.TextField(blank=True, null=True)),
                ('contactPerson', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('companyProfile', models.TextField()),
                ('news', models.TextField(blank=True, null=True)),
                ('newsLink', models.URLField(blank=True, null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('welfare', models.TextField(blank=True, null=True)),
                ('legalTagNames', models.TextField(blank=True, null=True)),
                ('tagNames', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('categoryDesc', models.TextField()),
            ],
            options={
                'verbose_name_plural': '公司',
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(null=True)),
                ('source_url', models.URLField(null=True)),
                ('name', models.TextField()),
                ('jobRole', models.IntegerField(null=True)),
                ('workType', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('workPeriod', models.TextField(null=True)),
                ('jobDesc', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('IndustryArea', models.TextField(null=True)),
                ('UpDate', models.DateField(null=True)),
                ('ApplyCount', models.IntegerField(null=True)),
                ('manageRespon', models.TextField(blank=True, null=True)),
                ('businessTrip', models.TextField(blank=True, null=True)),
                ('vacationPolicy', models.TextField(blank=True, null=True)),
                ('startWorkDay', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('salaryHigh', models.IntegerField(null=True)),
                ('salaryLow', models.IntegerField(null=True)),
                ('salaryType', models.IntegerField(null=True)),
                ('hireType', models.TextField(blank=True, null=True)),
                ('needEmployee', models.TextField(blank=True, null=True)),
                ('landmark', models.TextField(blank=True, null=True)),
                ('remoteWork', models.TextField(blank=True, null=True)),
                ('delegatedRecruit', models.TextField(blank=True, null=True)),
                ('roleDesc', models.JSONField(blank=True, null=True)),
                ('workExp', models.TextField(blank=True, null=True)),
                ('edu', models.TextField(blank=True, null=True)),
                ('major', models.JSONField(blank=True, null=True)),
                ('language', models.JSONField(blank=True, null=True)),
                ('localLanguage', models.JSONField(blank=True, null=True)),
                ('specialty', models.JSONField(blank=True, null=True)),
                ('skill', models.JSONField(blank=True, null=True)),
                ('certificate', models.JSONField(blank=True, null=True)),
                ('driverLicense', models.JSONField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=[], null=True), size=None)),
                ('import_date', models.DateField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobCompany', to='jobs.companys')),
            ],
            options={
                'verbose_name_plural': '職缺',
                'db_table': 'Job',
            },
        ),
        migrations.CreateModel(
            name='CompanySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(null=True)),
                ('source_url', models.URLField(null=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.companys')),
            ],
            options={
                'verbose_name_plural': '公司資料來源',
                'db_table': 'CompanySource',
            },
        ),
    ]
