# Generated by Django 3.2.8 on 2021-11-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companys',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companys',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companys',
            name='capital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companys',
            name='categoryDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companys',
            name='companyProfile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companys',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companys',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companys',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
