# Generated by Django 3.2.8 on 2021-11-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211129_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companys',
            name='newsLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
