# Generated by Django 3.2.9 on 2021-12-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_companys_newslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='alerted',
            field=models.BooleanField(default=False),
        ),
    ]
